### ISSUE TITLE
Couldn't import module nbt

### ISSUE THREAD

**Issue by Chy271** [DMBuce/mcexplore#8] opened 2022-06-25 12:44 UTC
I followed the installation path for other Distros. When running mcexplore I get the error:  
"Couldn't import module: nbt

Make sure you followed the install procedure:
        https://github.com/dmbuce/mcexplore#install"

But "find / -name nbt.py" returns "find: ‘/media/USB’: Input/output error
/home/mcserv/venv/python3/lib/python3.8/site-packages/nbt/nbt.py"

**Comment by DMBuce** [comment] 2022-06-25 15:19
Check that the first line of mcexplore uses the virtualenv's python and not the system python. For you I guess the first line should be:

    #!/home/mcserv/venv/python3/bin/python

If that's the first line and you're still getting the error, I'm not sure what the issue could be.

**Comment by Chy271** [comment] 2022-06-25 16:09
That's the first line

**Comment by DMBuce** [comment] 2022-06-26 14:03
What distro are you using?

What is the output of `echo import nbt | ~/venv/python3/bin/python` ?

**Comment by Chy271** [comment] 2022-06-28 08:53
Hi, sorry for the delayed reply:
I run ubuntu 20.04.4 server
The command returns nothing

**Comment by DMBuce** [comment] 2022-06-28 20:09
Hmm, I was expecting the command to show an ImportError. It's strange that you are able to import the nbt module, yet mcexplore can't. Maybe because the script uses a slightly different import statement. Does `echo from nbt import nbt | ~/venv/python3/bin/python` have any output?

I tried running through the install procedure on a newly installed Ubuntu 20.04 systemd-nspawn container and was not able to reproduce the issue. After installing the `wget` and `virtualenv` packages with apt, I was able to install and run mcexplore with the `--help` option. A transcript of the shell session is below.

Maybe you could try moving your current virtualenv aside with `mv ~/venv ~/venv.back` and run through the install procedure again.

    Ubuntu 20.04 LTS football console
    
    football login: root
    Password: 
    Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.15.19-1-lts x86_64)
    
     * Documentation:  https://help.ubuntu.com
     * Management:     https://landscape.canonical.com
     * Support:        https://ubuntu.com/advantage
    
    The programs included with the Ubuntu system are free software;
    the exact distribution terms for each program are described in the
    individual files in /usr/share/doc/*/copyright.
    
    Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
    applicable law.
    
    root@football:~# apt install wget
    Reading package lists... Done
    Building dependency tree... Done
    The following NEW packages will be installed:
      wget
    0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
    Need to get 349 kB of archives.
    After this operation, 1016 kB of additional disk space will be used.
    Get:1 http://archive.ubuntu.com/ubuntu focal/main amd64 wget amd64 1.20.3-1ubuntu1 [349 kB]
    Fetched 349 kB in 11s (33.1 kB/s)
    Selecting previously unselected package wget.
    (Reading database ... 11586 files and directories currently installed.)
    Preparing to unpack .../wget_1.20.3-1ubuntu1_amd64.deb ...
    Unpacking wget (1.20.3-1ubuntu1) ...
    Setting up wget (1.20.3-1ubuntu1) ...
    root@football:~# apt install virtualenv
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following additional packages will be installed:
      python-pip-whl python3-appdirs python3-distlib python3-distutils python3-filelock
      python3-importlib-metadata python3-lib2to3 python3-more-itertools
      python3-virtualenv python3-zipp
    The following NEW packages will be installed:
      python-pip-whl python3-appdirs python3-distlib python3-distutils python3-filelock
      python3-importlib-metadata python3-lib2to3 python3-more-itertools
      python3-virtualenv python3-zipp virtualenv
    0 upgraded, 11 newly installed, 0 to remove and 0 not upgraded.
    Need to get 2268 kB of archives.
    After this operation, 4718 kB of additional disk space will be used.
    Do you want to continue? [Y/n] y
    Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 python-pip-whl all 20.0.2-5ubuntu1 [1799 kB]
    Get:2 http://archive.ubuntu.com/ubuntu focal/main amd64 python3-appdirs all 1.4.3-2.1 [10.8 kB]
    Get:3 http://archive.ubuntu.com/ubuntu focal/universe amd64 python3-distlib all 0.3.0-1 [116 kB]
    Get:4 http://archive.ubuntu.com/ubuntu focal/main amd64 python3-lib2to3 all 3.8.2-1ubuntu1 [74.1 kB]
    Get:5 http://archive.ubuntu.com/ubuntu focal/main amd64 python3-distutils all 3.8.2-1ubuntu1 [140 kB]
    Get:6 http://archive.ubuntu.com/ubuntu focal/universe amd64 python3-filelock all 3.0.12-2 [7948 B]
    Get:7 http://archive.ubuntu.com/ubuntu focal/main amd64 python3-more-itertools all 4.2.0-1build1 [39.4 kB]
    Get:8 http://archive.ubuntu.com/ubuntu focal/main amd64 python3-zipp all 1.0.0-1 [5312 B]
    Get:9 http://archive.ubuntu.com/ubuntu focal/main amd64 python3-importlib-metadata all 1.5.0-1 [9992 B]
    Get:10 http://archive.ubuntu.com/ubuntu focal/universe amd64 python3-virtualenv all 20.0.17-1 [63.4 kB]
    Get:11 http://archive.ubuntu.com/ubuntu focal/universe amd64 virtualenv all 20.0.17-1 [2132 B]
    Fetched 2268 kB in 7s (328 kB/s)                                                     
    Selecting previously unselected package python-pip-whl.
    (Reading database ... 11597 files and directories currently installed.)
    Preparing to unpack .../00-python-pip-whl_20.0.2-5ubuntu1_all.deb ...
    Unpacking python-pip-whl (20.0.2-5ubuntu1) ...
    Selecting previously unselected package python3-appdirs.
    Preparing to unpack .../01-python3-appdirs_1.4.3-2.1_all.deb ...
    Unpacking python3-appdirs (1.4.3-2.1) ...
    Selecting previously unselected package python3-distlib.
    Preparing to unpack .../02-python3-distlib_0.3.0-1_all.deb ...
    Unpacking python3-distlib (0.3.0-1) ...
    Selecting previously unselected package python3-lib2to3.
    Preparing to unpack .../03-python3-lib2to3_3.8.2-1ubuntu1_all.deb ...
    Unpacking python3-lib2to3 (3.8.2-1ubuntu1) ...
    Selecting previously unselected package python3-distutils.
    Preparing to unpack .../04-python3-distutils_3.8.2-1ubuntu1_all.deb ...
    Unpacking python3-distutils (3.8.2-1ubuntu1) ...
    Selecting previously unselected package python3-filelock.
    Preparing to unpack .../05-python3-filelock_3.0.12-2_all.deb ...
    Unpacking python3-filelock (3.0.12-2) ...
    Selecting previously unselected package python3-more-itertools.
    Preparing to unpack .../06-python3-more-itertools_4.2.0-1build1_all.deb ...
    Unpacking python3-more-itertools (4.2.0-1build1) ...
    Selecting previously unselected package python3-zipp.
    Preparing to unpack .../07-python3-zipp_1.0.0-1_all.deb ...
    Unpacking python3-zipp (1.0.0-1) ...
    Selecting previously unselected package python3-importlib-metadata.
    Preparing to unpack .../08-python3-importlib-metadata_1.5.0-1_all.deb ...
    Unpacking python3-importlib-metadata (1.5.0-1) ...
    Selecting previously unselected package python3-virtualenv.
    Preparing to unpack .../09-python3-virtualenv_20.0.17-1_all.deb ...
    Unpacking python3-virtualenv (20.0.17-1) ...
    Selecting previously unselected package virtualenv.
    Preparing to unpack .../10-virtualenv_20.0.17-1_all.deb ...
    Unpacking virtualenv (20.0.17-1) ...
    Setting up python3-more-itertools (4.2.0-1build1) ...
    Setting up python3-filelock (3.0.12-2) ...
    Setting up python3-distlib (0.3.0-1) ...
    Setting up python3-zipp (1.0.0-1) ...
    Setting up python-pip-whl (20.0.2-5ubuntu1) ...
    Setting up python3-lib2to3 (3.8.2-1ubuntu1) ...
    Setting up python3-appdirs (1.4.3-2.1) ...
    Setting up python3-distutils (3.8.2-1ubuntu1) ...
    Setting up python3-importlib-metadata (1.5.0-1) ...
    Setting up python3-virtualenv (20.0.17-1) ...
    Setting up virtualenv (20.0.17-1) ...
    root@football:~# adduser mcserv
    Adding user `mcserv' ...
    Adding new group `mcserv' (1000) ...
    Adding new user `mcserv' (1000) with group `mcserv' ...
    Creating home directory `/home/mcserv' ...
    Copying files from `/etc/skel' ...
    New password: 
    Retype new password: 
    passwd: password updated successfully
    Changing the user information for mcserv
    Enter the new value, or press ENTER for the default
    	Full Name []: 
    	Room Number []: 
    	Work Phone []: 
    	Home Phone []: 
    	Other []: 
    Is the information correct? [Y/n] y
    root@football:~# id mcserv
    uid=1000(mcserv) gid=1000(mcserv) groups=1000(mcserv)
    root@football:~# su - mcserv
    mcserv@football:~$ virtualenv -p python3 ~/venv/python3
    created virtual environment CPython3.8.2.final.0-64 in 448ms
      creator CPython3Posix(dest=/home/mcserv/venv/python3, clear=False, global=False)
      seeder FromAppData(download=False, ipaddr=latest, certifi=latest, CacheControl=latest, packaging=latest, distlib=latest, six=latest, wheel=latest, pkg_resources=latest, webencodings=latest, msgpack=latest, colorama=latest, idna=latest, chardet=latest, contextlib2=latest, pytoml=latest, appdirs=latest, pip=latest, lockfile=latest, retrying=latest, html5lib=latest, pyparsing=latest, setuptools=latest, distro=latest, urllib3=latest, requests=latest, pep517=latest, progress=latest, via=copy, app_data_dir=/home/mcserv/.local/share/virtualenv/seed-app-data/v1.0.1.debian)
      activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
    mcserv@football:~$ ~/venv/python3/bin/pip install nbt
    Collecting nbt
      Downloading NBT-1.5.1-py2.py3-none-any.whl (25 kB)
    Installing collected packages: nbt
    Successfully installed nbt-1.5.1
    mcserv@football:~$ wget https://raw.githubusercontent.com/DMBuce/mcexplore/master/mcexplore.py
    --2022-06-28 14:41:51--  https://raw.githubusercontent.com/DMBuce/mcexplore/master/mcexplore.py
    Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
    Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 14546 (14K) [text/plain]
    Saving to: 'mcexplore.py'
    
    mcexplore.py          100%[=======================>]  14.21K  --.-KB/s    in 0.004s  
    
    2022-06-28 14:41:57 (3.66 MB/s) - 'mcexplore.py' saved [14546/14546]
    
    mcserv@football:~$ chmod +x mcexplore.py
    mcserv@football:~$ sed -i "1s,^#\!.*,#\!$HOME/venv/python3/bin/python," mcexplore.py
    mcserv@football:~$ ./mcexplore.py --help
    usage: mcexplore [-c COMMAND] [-d DIMENSION] [-p PATH] [-r] [-x XORIGIN]
                     [-z ZORIGIN] [-q] [-v] [-V] [-h]
                     xsize [zsize]
    
    Use a minecraft server jar to generate a rectangular section of the world.
    
    positional arguments:
      xsize                 The size to generate in the x direction. Measured in chunks
                            (16x16 blocks) by default (but see the -r option, below).
                            Must be greater than 25 chunks.
      zsize                 The size to generate in the z direction. Measured in chunks
                            (16x16 blocks) by default (but see the -r option, below).
                            Must be greater than 25 chunks. Defaults to the value
                            provided for 'xsize'.
    
    optional arguments:
      -c COMMAND, --command COMMAND
                            The command used to start the server. Defaults to 'java -jar
                            minecraft_server.jar nogui'.
      -d DIMENSION, --dimension DIMENSION
                            The ID and region folder of the dimension to generate.
                            Relative folder paths are interpreted relative to '--path'.
                            Defaults to 'minecraft:overworld=world/region'.
      -p PATH, --path PATH  The working directory to use when running the server.
                            Defaults to the current directory (.).
      -r, --regions         Use units of regions (32x32 chunks) instead of chunks for
                            'xsize' and 'zsize'.
      -x XORIGIN            The X offset to generate land around. Defaults to the server
                            spawn point.
      -z ZORIGIN            The Z offset to generate land around. Defaults to the server
                            spawn point.
      -q, --quiet           Suppress minecraft server output. This is the default
                            behavior.
      -v, --verbose         Show minecraft server output.
      -V, --version         Show version number and exit.
      -h, --help            Show this help message and exit.

Not sure if this helps but here are the versions of various software used in the setup:

    mcserv@football:~$ cat /etc/os-release 
    NAME="Ubuntu"
    VERSION="20.04 LTS (Focal Fossa)"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Ubuntu 20.04 LTS"
    VERSION_ID="20.04"
    HOME_URL="https://www.ubuntu.com/"
    SUPPORT_URL="https://help.ubuntu.com/"
    BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
    PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
    VERSION_CODENAME=focal
    UBUNTU_CODENAME=focal
    mcserv@football:~$ virtualenv --version
    virtualenv 20.0.17 from /usr/lib/python3/dist-packages/virtualenv/__init__.py
    mcserv@football:~$ ~/venv/python3/bin/python --version
    Python 3.8.2
    mcserv@football:~$ ~/venv/python3/bin/pip --version
    pip 20.0.2 from /home/mcserv/venv/python3/lib/python3.8/site-packages/pip (python 3.8)
    mcserv@football:~$ ls ~/venv/python3/lib/python3.8/site-packages/nbt/
    __init__.py  __pycache__  chunk.py  nbt.py  region.py  world.py

**Comment by Chy271** [comment] 2022-06-29 12:10
Ok i don't really know why it works now but what I did is:
I removed python and just reinstalled virtualenv (and dependencies). Now it works.
I did this because I saw that your installation was using Python 3.8.2 whereas mine was using 3.10.2.

**Comment by DMBuce** [comment] 2022-06-30 12:29
Strange! Glad you got it working.

**Closed as completed by DMBuce** 2022-06-30 12:29 UTC
